# Pandas

In [11]:
import pandas as pd
import numpy as np

### Object creation

##### Series

In [ ]:
# case 1: use the dictionary to create an pandas object
dict_v = {'a':0, 'b':1, 'c':2, 'd':3}
sr = pd.Series(dict_v)    # sr - series - one-dimention dictionary
print(sr)

# case 2: use key-value objects
v = [0, 1, 2, 3]
k = ['a', 'b', 'c', 'd']
sr = pd.Series(v, index = k)
print(sr)

a    0
b    1
c    2
d    3
dtype: int64
a    0
b    1
c    2
d    3
dtype: int64
Index(['a', 'b', 'c', 'd'], dtype='object')
[0 1 2 3]


In [9]:
# view the index attribute
print(sr.index)
# view the value attribute
print(sr.values)

Index(['a', 'b', 'c', 'd'], dtype='object')
[0 1 2 3]


in any way(table, array, tensor), the values will be an array
##### DataFrame
it has 3 attributes: values, index, columns

1st way

In [ ]:
# age
v1 = [53, 64, 72, 82]
i = ['No.1', 'No.2', 'No.3', 'No.4']
sr1 = pd.Series(v1, index = i)
sr1

No.1    53
No.2    64
No.3    72
No.4    82
dtype: int64

In [7]:
# sex
v2 = ['female', 'male', 'male', 'female']
i = ['No.1', 'No.2', 'No.3', 'No.4']
sr2 = pd.Series(v2, index = i)
sr2

No.1    female
No.2      male
No.3      male
No.4    female
dtype: object

In [ ]:
# create a dataframe object
df = pd.DataFrame({'age':sr1, 'sex':sr2})    # df-function will include all the index in sr1 and sr2, and the missing place will be 'NaN'
df

age     sex
No.1   53  female
No.2   64    male
No.3   72    male
No.4   82  female

2nd way - most straightforward\
\
pass parameters to the pd.DataFrame(), which requires three parameters:\
1st: the values (array)\
attention: if the value-types diverge, it will choose the type with the best compatibility as the value-type\
2nd: the row labels index\
3rd: the column labels columns\
\
the index and columns parameters can be omitted, and after omission, they will be sequential numbers starting from 0

In [13]:
# create values
v = np.array([[53, 'female'], [64, 'male'], [72, 'male'], [82, 'female']])
i = ['No.1', 'No.2', 'No.3', 'No.4']
c = ['age', 'sex']

In [14]:
# create a dataframe
df = pd.DataFrame(v, index = i, columns = c)
df

age     sex
No.1  53  female
No.2  64    male
No.3  72    male
No.4  82  female

the attributes of dataframe

In [ ]:
print(df.values)
print(df.index)
print(df.columns)

[['53' 'female']
 ['64' 'male']
 ['72' 'male']
 ['82' 'female']]
Index(['No.1', 'No.2', 'No.3', 'No.4'], dtype='object')
Index(['age', 'sex'], dtype='object')


In [19]:
# focus on the values
arr = df.values
print(arr)
arr = arr[:, 0]   		# get the first col
print(arr)        		# we can know that the elements are all strings
arr = arr.astype(int)   # change it into int-type
print(arr)

[['53' 'female']
 ['64' 'male']
 ['72' 'male']
 ['82' 'female']]
['53' '64' '72' '82']
[53 64 72 82]
