# NumPy

In [1]:
import numpy as np

In [ ]:
# Initiate
arr1 = np.array([1, 2, 3])     #int type
print(arr1)

arr2 = np.array([1.0, 2, 3])   #float type
print(arr2)

[1 2 3]
[1. 2. 3.]


In [ ]:
# Change element
arr1[0] = 100.1   #aotomatically changed into 100(int)
print(arr1)

#Change type
arr1 = arr1.astype(float)
print(arr1)

arr = np.array([1, 2, 3])
print(arr)
print(arr + 0.0)
print(arr * 1.0)
print(arr / 1)

[100.1   2.    3. ]
[100.1   2.    3. ]
[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]


In [ ]:
# high-dimention array
arr1 = np.ones(3)              #1-d
arr2 = np.ones((1, 2))         #2-d
arr3 = np.ones(((1, 2, 3)))    #3-d

print(arr1, arr1.shape)
print(arr2, arr2.shape)
print(arr3, arr3.shape)

[1. 1. 1.] (3,)
[[1. 1.]] (1, 2)
[[[1. 1. 1.]
  [1. 1. 1.]]] (1, 2, 3)


In [ ]:
# reshape
arr1 = np.arange(10)         # array + range 操作
arr2 = arr1.reshape(2, -1)   #-1表示自动计算，当然也可以自己填数值
print(arr1)
print(arr2)

arr2 = np.arange(10).reshape(2, -1)
arr1 = arr2.reshape(1, -1)
print(arr1)
print(arr2)

arr3 = arr1.reshape(-1, 1)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4 5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [13]:
# ones(), zeros()
arr1 = np.zeros((1, 5))
arr2 = np.ones((2, 3))
arr3 = 0.25 * np.ones((2, 3))

print(arr1)
print(arr2)
print(arr3)

[[0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.25 0.25 0.25]
 [0.25 0.25 0.25]]


In [ ]:
# random

# 0-1均匀分布
arr = np.random.random(5)
print(arr)

# 随机整数
arr = np.random.randint(30, 70, (2, 3))
print(arr)

# 正态分布
arr = np.random.normal(0, 1, (2, 3))
print(arr)

[0.82927213 0.31512695 0.25061807 0.11792133 0.01238074]
[[58 52 63]
 [58 50 48]]
[[ 0.67434285  1.43141391  1.37517331  0.81949474 -0.1009069   1.11422929
  -0.89702408  2.06630407  0.03258563  0.51558852  0.73267689  1.88435819
  -0.18054969 -0.09582057 -1.44330037 -0.96484791 -1.04367097 -0.16178371
   0.19881195 -0.04456437 -0.43968056  0.06692758  0.21628178  1.09964192
   0.96437339  0.63422105 -0.47959739  1.34751054  0.47843279 -1.59651723]
 [-0.3745513   0.9005898   0.6775681   1.31512342  0.76758939  0.47688089
   1.89316436  0.09856835 -0.85939626  1.31989005 -1.25128287  1.89073923
   0.94557207  2.04955293  0.37740168 -0.91474559  0.68460784 -0.61226504
   1.50101209  0.29356379  1.4815317   0.81996699 -0.51895575  0.6705374
   0.23167179 -1.84261865 -0.44767119 -0.56936939  0.22461621 -0.48456241]]
