# NumPy

In [1]:
import numpy as np

In [2]:
# Initiate
arr1 = np.array([1, 2, 3])     #int type
print(arr1)

arr2 = np.array([1.0, 2, 3])   #float type
print(arr2)

[1 2 3]
[1. 2. 3.]


In [3]:
# Change element
arr1[0] = 100.1   #aotomatically changed into 100(int)
print(arr1)

#Change type
arr1 = arr1.astype(float)
print(arr1)

arr = np.array([1, 2, 3])
print(arr)
print(arr + 0.0)
print(arr * 1.0)
print(arr / 1)

[100   2   3]
[100.   2.   3.]
[1 2 3]
[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]


In [4]:
# high-dimention array
arr1 = np.ones(3)              #1-d
arr2 = np.ones((1, 2))         #2-d
arr3 = np.ones(((1, 2, 3)))    #3-d

print(arr1, arr1.shape)
print(arr2, arr2.shape)
print(arr3, arr3.shape)

[1. 1. 1.] (3,)
[[1. 1.]] (1, 2)
[[[1. 1. 1.]
  [1. 1. 1.]]] (1, 2, 3)


In [5]:
# reshape
arr1 = np.arange(10)         # array + range 操作
arr2 = arr1.reshape(2, -1)   #-1表示自动计算，当然也可以自己填数值
print(arr1)
print(arr2)

arr2 = np.arange(10).reshape(2, -1)
arr1 = arr2.reshape(1, -1)
print(arr1)
print(arr2)

arr3 = arr1.reshape(-1, 1)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4 5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [6]:
# ones(), zeros()
arr1 = np.zeros((1, 5))
arr2 = np.ones((2, 3))
arr3 = 0.25 * np.ones((2, 3))

print(arr1)
print(arr2)
print(arr3)

[[0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.25 0.25 0.25]
 [0.25 0.25 0.25]]


In [7]:
# random

# 0-1均匀分布
arr = np.random.random(5)
print(arr)

# 随机整数
arr = np.random.randint(30, 70, (2, 3))
print(arr)

# 正态分布
arr = np.random.normal(0, 1, (2, 3))
print(arr)

[0.65703766 0.03285534 0.31401669 0.43663209 0.17791981]
[[32 64 59]
 [46 66 60]]
[[-1.94633599 -0.2364321  -0.89552878]
 [-0.21829027  0.7484492   1.33195579]]


In [8]:
# index
arr = np.arange(10)
print(arr[4])

arr1 = np.arange(10).reshape(2, -1)
print(arr1[1, 3])

# fancy index
print(arr[[0, 2]])
print(arr1[[0, 0, 1], [0, 4, 3]])   #前后一一对应行和列

print(arr1)
arr1[[0, 0, 1], [0, 4, 3]] = 10     #修改
print(arr1)

4
8
[0 2]
[0 4 8]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10  1  2  3 10]
 [ 5  6  7 10  9]]


In [9]:
# slice ------slice中的东西是引用!!!
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr[2:])
print(arr[:2])
print(arr[::2])

arr = np.arange(20).reshape(4, -1)
print(arr[::2, [0, 1, 4]])        #前面对应行，后面对应列
print(arr[0:2, :])                #可以简写（把 , : 去掉）
print(arr[:, 2::2])

[2 3 4 5]
[0 1]
[0 2 4]
[[ 0  1  4]
 [10 11 14]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [10]:
# copy
# case 1
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr)
arr1 = arr
arr1[0] = 10000
print(arr)       #明显发生了变化（说明 = 执行浅拷贝工作）

# case 2
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr)
arr_slice = arr[2:]
arr_slice[0] = 10000
print(arr)       #明显发生了变化

arr = np.array([0, 1, 2, 3, 4, 5])
print(arr)
arr_slice = arr[2:].copy()     #copy()
arr_slice[0] = 10000
print(arr)       #无变化（深拷贝）

[0 1 2 3 4 5]
[10000     1     2     3     4     5]
[0 1 2 3 4 5]
[    0     1 10000     3     4     5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [11]:
# T
arr1 = np.arange(6)
arr2 = arr1.reshape((1, -1))    # T仅对矩阵有效，因此要先将其转化为矩阵
arr3 = arr2.T					# 转置操作
print(arr1)
print(arr2)
print(arr3)

[0 1 2 3 4 5]
[[0 1 2 3 4 5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [12]:
# 翻转

# 向量
arr1 = np.arange(10)
print(arr1)
arr_ud = np.flipud(arr1)   #翻转向量
print(arr_ud)

# 矩阵
arr2 = np.arange(20).reshape((4, -1))
print(arr2)
arr_lr = np.fliplr(arr2)   #内层翻转
print(arr_lr)
arr_ud = np.flipud(arr2)   #外层翻转
print(arr_ud)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


In [13]:
# 拼接
# 向量
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate([arr1, arr2])
print(arr)

#矩阵
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
# 行拼接
arr = np.concatenate([arr1, arr2], axis = 0)    #axis默认是0
print(arr)
# 列拼接
arr = np.concatenate([arr1, arr2], axis = 1)
print(arr)

[1 2 3 4 5 6]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [14]:
# 分裂
# 向量
arr = np.arange(10)
arr1, arr2, arr3 = np.split(arr, [2, 8])
print(arr1)
print(arr2)
print(arr3)

#矩阵
arr = np.arange(8).reshape(2, -1)
arr1, arr2 = np.split(arr, [1], axis = 0)
print(arr1)
print(arr2)
arr1, arr2, arr3 = np.split(arr, [1, 3], axis = 1)
print(arr1)
print(arr2)
print(arr3)

[0 1]
[2 3 4 5 6 7]
[8 9]
[[0 1 2 3]]
[[4 5 6 7]]
[[0]
 [4]]
[[1 2]
 [5 6]]
[[3]
 [7]]


In [15]:
# 运算
# 数组之间的运算是逐元素的运算
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.arange(10, 20).reshape(2, -1)
print(arr1 + arr2)
print(arr1 * arr2)
print(1.0 * arr1 / arr2)

[[10 12 14 16 18]
 [20 22 24 26 28]]
[[  0  11  24  39  56]
 [ 75  96 119 144 171]]
[[0.         0.09090909 0.16666667 0.23076923 0.28571429]
 [0.33333333 0.375      0.41176471 0.44444444 0.47368421]]


In [16]:
# 广播（自动拓展成能相乘的东西）
arr1 = np.arange(4)
arr2 = np.arange(4).reshape(-1, 1)
print(arr1)
print(arr2)
print(arr1 * arr2)    #最好不要这样，因为难看

[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]


###### 矩阵运算函数

In [17]:
## dot(arr1, arr2)

# 向量内积
arr1 = np.arange(5)
arr2 = arr1.copy()
print(np.dot(arr1, arr2))

# 矩阵乘矩阵（向量自动转换为矩阵）
# case 1
arr1 = np.arange(5)
arr2 = np.arange(15).reshape(5, -1)
print(np.dot(arr1, arr2))
# case 2
arr1 = np.arange(15).reshape(-1, 3)
arr2 = np.arange(3)
print(np.dot(arr1, arr2))
# case 3
arr1 = np.arange(10).reshape(-1, 5)
arr2 = np.arange(15).reshape(5, -1)
print(np.dot(arr1, arr2))

30
[ 90 100 110]
[ 5 14 23 32 41]
[[ 90 100 110]
 [240 275 310]]


In [18]:
# 绝对值
arr = np.array([-100, 0, 100])
arr_abs = np.abs(arr)
print(arr_abs)

[100   0 100]


In [19]:
# 三角函数（rad）
arr = np.arange(3)
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

[0.         0.84147098 0.90929743]
[ 1.          0.54030231 -0.41614684]
[ 0.          1.55740772 -2.18503986]


In [20]:
# 指数函数
arr = np.arange(3)
print("x = ", arr)
print("2 ^ x = ", 2 ** arr)
print("e ^ x = ", np.exp(arr))

x =  [0 1 2]
2 ^ x =  [1 2 4]
e ^ x =  [1.         2.71828183 7.3890561 ]


In [21]:
# 对数函数
arr = np.arange(1, 5)
print("x = ", arr)
print("ln(x) = ", np.log(arr))
print("log2(x) = ", np.log(arr) / np.log(2))
print("log(x) = ", np.log(arr) / np.log(10))

x =  [1 2 3 4]
ln(x) =  [0.         0.69314718 1.09861229 1.38629436]
log2(x) =  [0.        1.        1.5849625 2.       ]
log(x) =  [0.         0.30103    0.47712125 0.60205999]


In [22]:
# 最大值，最小值函数
arr = np.random.random((2, 3))
print(arr)
print("对每列求最大值：", np.max(arr, axis = 0))
print("对每列求最小值：", np.min(arr, axis = 0))
print("对每行求最大值：", np.max(arr, axis = 1))
print("对每行求最小值：", np.min(arr, axis = 1))
print("整体最大值：", np.max(arr))
print("整体最小值：", np.min(arr))

[[0.63668513 0.48558304 0.09134985]
 [0.606016   0.33209206 0.07263151]]
对每列求最大值： [0.63668513 0.48558304 0.09134985]
对每列求最小值： [0.606016   0.33209206 0.07263151]
对每行求最大值： [0.63668513 0.606016  ]
对每行求最小值： [0.09134985 0.07263151]
整体最大值： 0.6366851273500583
整体最小值： 0.07263151488194175


In [23]:
# 求和函数sum()
arr = np.arange(20).reshape(4, -1)
print(arr)
print("对列求和：", np.sum(arr, axis = 0))
print("对行求和：", np.sum(arr, axis = 1))
print("整体求和：", np.sum(arr))

# 求积函数同理 prod()
# 均值函数 mean()
# 标准差函数 std()
# 安全函数：在函数名前面加上nan，自动忽略缺失值，比如nansum(), nanmean()

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
对列求和： [30 34 38 42 46]
对行求和： [10 35 60 85]
整体求和： 190
